src/Entity/API/FutureSupply.php
<?php
/**
 * @author JKetelaar
 */

namespace App\Entity\API;

class FutureSupply
{
    /**
     * @var string
     */
    private $id;

    /**
     * @var float
     */
    private $savings;

    /**
     * @var int
     */
    private $supplierId;

    /**
     * @var string
     */
    private $supplier;

    /**
     * @var string
     */
    private $logo;

    /**
     * @var string
     */
    private $tariffType;

    /**
     * @var int
     */
    private $paymentType;

    /**
     * @var float
     */
    private $expectedSpend;

    /**
     * FutureSupply constructor.
     * @param string $id
     * @param float $savings
     * @param int $supplierId
     * @param string $supplier
     * @param string $logo
     * @param string $tariffType
     * @param int $paymentType
     */
    public function __construct(string $id, float $savings, int $supplierId, string $supplier, string $logo, string $tariffType, int $paymentType, float $expectedSpend)
    {
        $this->id = $id;
        $this->savings = $savings;
        $this->supplierId = $supplierId;
        $this->supplier = $supplier;
        $this->logo = $logo;
        $this->tariffType = $tariffType;
        $this->paymentType = $paymentType;
        $this->expectedSpend = $expectedSpend;
    }

    public static function fromSupplierJSON(array $json): FutureSupply
    {
        return new FutureSupply(
            $json['id'],
            $json['expectedAnnualSavings'],
            $json['supplier']['id'],
            $json['supplier']['name'],
            $json['supplyDetails']['logo']['uri'],
            $json['tariffType'],
            $json['supplyDetails']['paymentMethod']['id'],
            $json['expectedAnnualSpend']
        );
    }

    /**
     * @return string
     */
    public function getId(): string
    {
        return $this->id;
    }

    /**
     * @return float
     */
    public function getSavings(): float
    {
        return number_format($this->savings, 2);
    }

    /**
     * @return float
     */
    public function getSavingsPerMonth(): float
    {
        return number_format($this->savings / 12, 2);
    }

    /**
     * @return int
     */
    public function getSupplierId(): int
    {
        return $this->supplierId;
    }

    /**
     * @return string
     */
    public function getSupplier(): string
    {
        return $this->supplier;
    }

    /**
     * @return string
     */
    public function getLogo(): string
    {
        return $this->logo;
    }

    /**
     * @return string
     */
    public function getTariffType(): string
    {
        return $this->tariffType;
    }

    /**
     * @return int
     */
    public function getPaymentType(): int
    {
        return $this->paymentType;
    }

    /**
     * @return float
     */
    public function getExpectedSpend(): float
    {
        return number_format($this->expectedSpend, 2);
    }

    /**
     * @return float
     */
    public function getExpectedSpendPerMonth(): float
    {
        return number_format($this->expectedSpend / 12, 2);
    }
}

src/Controller/SwitchController.php
<?php

namespace App\Controller;

use App\Entity\API\Supplier;
use App\Entity\PersonalInformation;
use App\Entity\Quote;
use App\Form\QuoteStepFourType;
use App\Service\SwitchException;
use App\Service\SwitchManager;
use NumberFormatter;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\RedirectResponse;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

/**
 * Class SwitchController
 * @package App\Controller
 *
 * @Route("/switch/step")
 */
class SwitchController extends AbstractController
{
    /**
     * @param Request $request
     * @return RedirectResponse|Response
     *
     * @Route("/5", name="switch_step_5")
     */
    public function switchStepFive(Request $request)
    {
        return $this->render(
            'switch/step_5.html.twig'
        );
    }

    /**
     * @param Request $request
     * @return RedirectResponse|Response
     *
     * @Route("/4", name="switch_step_4")
     */
    public function switchStepFour(Request $request)
    {
        if (($quote = $this->getQuote($request)) === null) {
            return $this->redirectToHome();
        }

        if (($personalInformation = $quote->getPersonalInformation()) === null) {
            $personalInformation = new PersonalInformation();
        }

        $form = $this->createForm(QuoteStepFourType::class, $personalInformation);

        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()) {
            $personalInformation = $form->getData();
            $quote->setPersonalInformation($personalInformation);

            $this->getDoctrine()->getManager()->persist($personalInformation);
            $this->getDoctrine()->getManager()->persist($quote);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('switch_step_5');
        }

        return $this->render(
            'switch/step_4.html.twig',
            [
                'form' => $form->createView(),
            ]
        );
    }

    /**
     * @param Request $request
     * @return Quote|null
     */
    private function getQuote(Request $request): ?Quote
    {
        $id = $request->getSession()->get('quote');

        if ($id === null) {
            return null;
        }

        return $this->getDoctrine()->getRepository(Quote::class)->find($id);
    }

    /**
     * @param array|null $errors
     * @return RedirectResponse
     */
    private function redirectToHome(?array $errors = null): RedirectResponse
    {
        return $this->redirectToRoute('home', ['errors' => $errors]);
    }

    /**
     * @param int $step
     * @param Request $request
     * @param SwitchManager $switchManager
     * @return RedirectResponse|Response
     *
     * @Route("/{step}", name="switch_step")
     */
    public function switchStep(int $step, Request $request, SwitchManager $switchManager)
    {
        $numberFormatter = new NumberFormatter('en', NumberFormatter::SPELLOUT);
        $stepFormType = 'App\Form\QuoteStep'.ucfirst($numberFormatter->format($step)).'Type';

        return $this->nextStep($request, $step, $step + 1, $stepFormType, $switchManager);
    }

    /**
     * @param Request $request
     * @param int $currentStep
     * @param int $nextStep
     * @param string $formClass
     * @param SwitchManager $switchManager
     * @return RedirectResponse|Response
     */
    private function nextStep(Request $request, int $currentStep, int $nextStep, string $formClass, SwitchManager $switchManager)
    {
        if (($quote = $this->getQuote($request)) === null) {
            return $this->redirectToHome();
        }

        $switchManager->setQuote($quote);

        $suppliers = null;
        $options = [];
        if ($currentStep === 1) {
            $suppliers = [];
            $plans = [];
            /** @var Supplier $supplier */
            try {
                foreach ($switchManager->getSuppliers() as $supplier) {
                    $suppliers[$supplier->getName()] = $supplier->getId();
                    foreach ($supplier->getPlans() as $plan) {
                        $plans[$plan->getName()] = $plan->getId();
                    }
                }
            } catch (SwitchException $e) {
                return $this->redirectToHome($e->getErrors());
            }
            ksort($suppliers);
            $options['suppliers'] = $suppliers;
            $options['plans'] = $plans;
        } elseif ($currentStep === 2) {
            $options['payment_methods'] = $switchManager->getPaymentMethods();
        } elseif ($currentStep === 3) {
            $suppliers = $switchManager->getFutureSupplies();
            $options['suppliers'] = $suppliers;
        }

        $form = $this->createForm($formClass, $quote, $options);

        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            /** @var Quote $quote */
            $quote = $form->getData();

            if ($currentStep === 2) {
                if ($request->request->get('quote_step_two')['selectedGasSpend'] == '1') {
                    $quote->setSelectedGasSpend(true);
                    $quote->setGasUseKWH(null);
                } else {
                    $quote->setSelectedGasSpend(false);
                    $quote->setGasMoneyPerType(null);
                    $quote->setGasMoneySpend(null);
                }
                if ($request->request->get('quote_step_two')['selectedElecSpend'] == '1') {
                    $quote->setSelectedElecSpend(true);
                    $quote->setElecUseKWH(null);
                } else {
                    $quote->setSelectedElecSpend(false);
                    $quote->setElecMoneyPerType(null);
                    $quote->setElecMoneySpend(null);
                }
            }

            if ($request->request->get('quote_step_one') !== null && $request->request->get(
                    'quote_step_one'
                )['sameSupplier'] == '0') {
                $quote->setSameSupplier(false);
            }

            $this->getDoctrine()->getManager()->persist($quote);
            $this->getDoctrine()->getManager()->flush();

            return $this->redirectToRoute('switch_step', ['step' => $nextStep]);
        }


        return $this->render(
            'switch/step_'.$currentStep.'.html.twig',
            [
                'form' => $form->createView(),
                'suppliers' => $suppliers,
                'payment_methods' => ($currentStep === 3 ? $switchManager->getPaymentMethods(
                    true
                ) : null),
                'quote' => $quote
            ]
        );
    }
}

templates/switch/step_3.html.twig
{% extends 'base.html.twig' %}

{% block title %}Step 3{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('assets/css/forms.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/form3.css') }}" rel="stylesheet">
{% endblock %}

{% block navigation %}
    <nav class="navbar navbar-light bg-light">
        <span id="nav-brand">
        <a href="../../" target="_blank" class="navbar-brand">
            <img src="{{ asset('assets/images/switchboo_white.png') }}" class="img-fluid" alt=""/>
        </a>
        </span>

        <form class="form-inline">
            <a href="{{ path('switch_step', {'step': 2}) }}">
                <span class="navbar-text">
                    <span>Back</span>
                </span>
            </a>
        </form>
    </nav>
{% endblock %}

{% block body %}
    <div class="container-fluid" id="form-container">
        {{ form_errors(form) }}
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center" id="step-bars">

                <div class="step-bar"></div>
                <div class="step-bar"></div>
                <div class="step-bar active"></div>

            </div>
        </div>


        <div class="row">
            <div class="col-md-6 offset-md-3 text-center" id="step-text">
                <h5>Wow you can save <span id="save-total">£ {{ suppliers[0].savings }}</span> by switching over to <span
                            id="new-supplier">{{ suppliers[0].supplier }}</span>
                </h5>
                <p>This is the cheapest deal available</p>
            </div>
        </div>


        <!-- end of top bars -->


        <!-- main form content -->

        <div class="row">
            <div class="col-10 col-lg-8 col-xl-6 offset-xl-3 offset-lg-2 offset-1" id="form-control">
                {{ form_start(form) }}

                <div class="row result-row active" data-id="{{ suppliers[0].id }}">

                    <!-- image column -->
                    <div class="col-12 col-md-4">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="column-title supplier-title">Supplier</h5>
                            </div>
                            <div class="col-12">
                                <img src="{{ suppliers[0].logo }}">
                            </div>
                        </div>
                    </div>
                    <!-- end of image column -->


                    <!-- type column -->
                    <div class="col-12 col-md-3">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="column-title">Type</h5>
                            </div>
                            <div class="col-12">
                                <p class="column-inner-text r-m-bottom">{{ suppliers[0].tariffType }}</p>
                                <p class="column-inner-text">{{ payment_methods[suppliers[0].paymentType] }}</p>

                                <p class="column-inner-text">
                                    <a id="direct-debit-guarantee" class="btn btn-primary" data-toggle="modal"
                                       data-target="#myModal">
                                        <span>View tariff details</span>
                                    </a>
                                </p>
                            </div>
                        </div>
                    </div>
                    <!-- end of type column -->


                    <!-- personal projection column -->
                    <div class="col-12 col-md-3">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="column-title">Personal Projection</h5>
                            </div>
                            <div class="col-12">
                                <p class="column-inner-text r-m-bottom">£ {{ suppliers[0].expectedSpend }} per year</p>
                                <p class="column-inner-text">£ {{ suppliers[0].expectedSpendPerMonth }} per month</p>
                            </div>
                        </div>
                    </div>
                    <!-- end of personal projection column -->


                    <!-- savings column -->
                    <div class="col-12 col-md-2">
                        <div class="row">
                            <div class="col-12">
                                <h5 class="column-title">Savings</h5>
                            </div>
                            <div class="col-12">
                                <h5 class="column-price-value">£ {{ suppliers[0].savings }}</h5>
                            </div>
                        </div>
                    </div>
                    <!-- end of savings column -->

                </div>

                {% if suppliers | length > 1 %}
                    <div class="row">
                        <p id="view-more"><a>View more results</a></p>
                    </div>


                    <div class="hidden">

                        {% for supplier in suppliers %}
                            {% if loop.index > 1 %}
                                <div class="row result-row" data-id="{{ supplier.id }}">

                                    <!-- image column -->
                                    <div class="col-12 col-md-4">
                                        <div class="row">
                                            <div class="col-12">
                                                <h5 class="column-title supplier-title">Supplier</h5>
                                            </div>
                                            <div class="col-12">
                                                <img src="{{ supplier.logo }}">
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end of image column -->


                                    <!-- type column -->
                                    <div class="col-12 col-md-3">
                                        <div class="row">
                                            <div class="col-12">
                                                <h5 class="column-title">Type</h5>
                                            </div>
                                            <div class="col-12">
                                                <p class="column-inner-text r-m-bottom">{{ supplier.tariffType }}</p>
                                                <p class="column-inner-text">{{ payment_methods[supplier.paymentType] }}</p>

                                                <p class="column-inner-text">
                                                    <a id="direct-debit-guarantee" class="btn btn-primary"
                                                       data-toggle="modal"
                                                       data-target="#myModal">
                                                        <span>View tariff details</span>
                                                    </a>
                                                </p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end of type column -->


                                    <!-- personal projection column -->
                                    <div class="col-12 col-md-3">
                                        <div class="row">
                                            <div class="col-12">
                                                <h5 class="column-title">Personal Projection</h5>
                                            </div>
                                            <div class="col-12">
                                                <p class="column-inner-text r-m-bottom">£ {{ supplier.expectedSpend }} per
                                                    year</p>
                                                <p class="column-inner-text">£ {{ supplier.expectedSpendPerMonth }} per
                                                    month</p>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end of personal projection column -->


                                    <!-- savings column -->
                                    <div class="col-12 col-md-2">
                                        <div class="row">
                                            <div class="col-12">
                                                <h5 class="column-title">Savings</h5>
                                            </div>
                                            <div class="col-12">
                                                <h5 class="column-price-value">£ {{ supplier.savings }}</h5>
                                            </div>
                                        </div>
                                    </div>
                                    <!-- end of savings column -->

                                </div>
                            {% endif %}
                        {% endfor %}

                    </div>
                {% endif %}

                <input id="chosenSupplier" type="hidden" name="quote_step_three[chosenSupplier]"
                       value="{{ suppliers[0].id }}">

                <!-- next page button -->
                <div class="row question-row">
                    <div class="col-12 col-sm-8 offset-sm-2 col-md-5 offset-md-7 col-lg-5 offset-lg-7 col-xl-4 offset-xl-8">
                        {{ form_widget(form.submit) }}
                        <p class="next-lower-text">Good on you!</p>
                    </div>
                </div>
                <!-- end of next page button -->

                {{ form_end(form, {'render_rest': false}) }}
            </div>

        </div>

        <!-- end of main form content -->

        <!-- start of footer -->
        <div class="row" id="footer">
            <div class="col-12 text-center">
                <h4>If you get stuck, give us a a call on 0800 4211 3213</h4>
            </div>
        </div>
        <!-- end of footer -->

    </div>



    <div class="modal" id="myModal">
        <div class="modal-dialog">
            <div class="modal-content">

                <div class="modal-header">
                    <h5 class="modal-title">Tariff Details</h5>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>

                <!-- Modal body -->
                <div class="modal-body">
                    <h6>TODO: tarrif details here once API is configured to parse them</h6>
                </div>

            </div>
        </div>
    </div>

{% endblock %}

{% block javascripts %}

    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
            integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl"
            crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
            integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q"
            crossorigin="anonymous"></script>

    <script src="{{ asset('assets/js/forms.js') }}"></script>

    <script>
        $('.result-row').on("click", function () {
            $('#chosenSupplier').val($(this).data('id'));
        });
    </script>
{% endblock %}

templates/switch/step_5.html.twig
{% extends 'base.html.twig' %}

{% block title %}Step 5{% endblock %}

{% block stylesheets %}
    <link href="{{ asset('assets/css/forms.css') }}" rel="stylesheet">
    <link href="{{ asset('assets/css/form5.css') }}" rel="stylesheet">
{% endblock %}

{% block navigation %}
    <nav class="navbar navbar-light bg-light">
        <span id="nav-brand">
        <a href="../../" target="_blank" class="navbar-brand">
            <img src="{{ asset('assets/images/switchboo_white.png') }}" class="img-fluid" alt=""/>
        </a>
        </span>

        <form class="form-inline">
            <a href="{{ path('switch_step', {'step': 2}) }}">
                <span class="navbar-text">
                    <span>Back</span>
                </span>
            </a>
        </form>
    </nav>
{% endblock %}

{% block body %}
    <div class="container-fluid" id="form-container">
        <div class="row">
            <div class="col-md-6 offset-md-3 text-center" id="step-bars">

                <div class="step-bar"></div>
                <div class="step-bar"></div>
                <div class="step-bar active"></div>

            </div>
        </div>


        <div class="row">
            <div class="col-md-6 offset-md-3 text-center" id="step-text">
                <h5>Congratulations you saved <span id="save-total">302.71</span> by switching over to <span
                            id="new-supplier">British Gas</span></h5>
                <p>When that deal ends our system will automatically run another check and switch you to the cheapest
                    deal.</p>
            </div>
        </div>


        <!-- end of top bars -->


        <!-- main form content -->

        <div class="row">
            <div class="col-10 col-lg-8 offset-lg-2 offset-1" id="form-control">


                <!-- header -->
                <div class="row question-row">
                    <div class="col-12 question-title text-center">
                        <h5>After Switch FAQs</h5>
                    </div>
                </div>
                <!-- end of header -->

                <!-- first question -->
                <div class="row question-row">

                    <div class="col-12 question-title">
                        <h5>What happens now</h5>
                        <p>sample text sample text sample text sample text sample text sample text sample text sample
                            text sample text sample text sample text sample text sample text sample text sample text
                            sample text sample text sample text sample text sample text sample text </p>
                    </div>

                </div>
                <!-- end of first question -->


                <!-- second question -->
                <div class="row question-row">

                    <div class="col-12 question-title">
                        <h5>Do i need to contact my old supplier</h5>
                        <p>sample text sample text sample text sample text sample text sample text sample text sample
                            text sample text sample text sample text sample text sample text sample text sample text
                            sample text sample text sample text sample text sample text sample text </p>
                    </div>

                </div>
                <!-- end of second question -->


                <!-- third question -->
                <div class="row question-row">

                    <div class="col-12 question-title">
                        <h5>How do i contact switchboo</h5>
                        <p>sample text sample text sample text sample text sample text sample text sample text sample
                            text sample text sample text sample text sample text sample text sample text sample text
                            sample text sample text sample text sample text sample text sample text </p>
                    </div>

                </div>
                <!-- end of third question -->


                <!-- fourth question -->
                <div class="row question-row">

                    <div class="col-12 question-title">
                        <h5>How can i set up a family member or friend</h5>
                        <p>sample text sample text sample text sample text sample text sample text sample text sample
                            text sample text sample text sample text sample text sample text sample text sample text
                            sample text sample text sample text sample text sample text sample text </p>
                    </div>

                </div>
                <!-- end of fourth question -->


                <!-- fifth question -->
                <div class="row question-row">

                    <div class="col-12 question-title">
                        <h5>How long will the switch take</h5>
                        <p>sample text sample text sample text sample text sample text sample text sample text sample
                            text sample text sample text sample text sample text sample text sample text sample text
                            sample text sample text sample text sample text sample text sample text </p>
                    </div>

                </div>
                <!-- end of fifth question -->


                <!-- sixth question -->
                <div class="row question-row">

                    <div class="col-12 question-title">
                        <h5>What happens when my new deal ends</h5>
                        <p>sample text sample text sample text sample text sample text sample text sample text sample
                            text sample text sample text sample text sample text sample text sample text sample text
                            sample text sample text sample text sample text sample text sample text </p>
                    </div>

                </div>
                <!-- end of sixth question -->


                <!-- seventh question -->
                <div class="row question-row">

                    <div class="col-12 question-title">
                        <h5>How will i know who you've switched me too</h5>
                        <p>sample text sample text sample text sample text sample text sample text sample text sample
                            text sample text sample text sample text sample text sample text sample text sample text
                            sample text sample text sample text sample text sample text sample text </p>
                    </div>

                </div>
                <!-- end of seventh question -->
            </div>
        </div>
        <!-- end of main form content -->

        <!-- start of footer -->
        <div class="row" id="footer">
            <div class="col-12 text-center">
                <h4>If you get stuck, give us a a call on 0800 4211 3213</h4>
            </div>
        </div>
        <!-- end of footer -->

    </div>
{% endblock %}

{% block javascripts %}
    <script src="{{ asset('assets/js/forms.js') }}"></script>
{% endblock %}